apiVersion: v2
name: iris-classifier
description: Helm chart that deploys the Iris classification Flask service.
type: application
version: 0.1.0
appVersion: "0.1.0"
keywords:
  - mlops
  - flask
  - sklearn
maintainers:
  - name: Hari Jaiswal
